### ISSUE TITLE
Does not work with neovim

### ISSUE THREAD

**Issue by drfunjohn** [skanehira/docker-compose.vim#5]
DockerComposeConfig

```
Error detected while processing function docker_compose#command#config[6]..docker_compose#api#terminal[6]..
docker_compose#utils#check#has:
line    2:
E121: Undefined variable: a:features
E116: Invalid arguments for function docker_compose#utils#message#err
```

**Comment by skanehira** [comment]
@drfunjohn Sorry, this plugin is not supported in Neovim.
And this plugin is no longer to maintenance.
If you are using [denops-docker.vim](https://github.com/skanehira/denops-docker.vim), you can use `docker compose`  through `:Docker` command.
For example, `:Docker compose up` will be executed as `docker compose up` instead.
I recommend you using denops-docker.vim because I maintenance it.
